### ISSUE TITLE
The transcribed speech can only be transcribed for 30 seconds, can it be longer?

### ISSUE THREAD

**Issue by nicekate** [aiola-lab/whisper-medusa#14]
I tried the following methods:
The CHUNK_LENGTH constant was introduced to define the length (in seconds) of each audio clip.
A new process_audio_chunk function has been added to process individual audio clips.
In the evaluate_model function, we now calculate the total duration of the audio and then divide the audio into multiple segments for processing.
Each fragment is transcribed, and then the transcription results of all fragments are merged into the complete transcribed text.

**However, meaningless duplicate words may appear in the merged text**

Is there any expert who can solve it?
thank you

**Comment by YaelSegalFeldman** [comment]
Hi, we currently support audio files up to 30 seconds long, but we plan to extend support for longer durations in the future. As a temporary workaround, you can split the audio into smaller chunks.
