### ISSUE TITLE
Plans to release training codebase? 🤗

### ISSUE THREAD

**Issue by Vaibhavs10** [aiola-lab/whisper-medusa#17]
Hi again, VB from Hugging Face here, I was wondering if y'all have plans to release the training codebase as well!

Given Medusa heads don't perform as well on out-of-distribution data, and the community can potentially train more diverse heads?

Would be keen to collab on that! let me know what you think!

Cheers,
VB

**Comment by AvivSham** [comment]
Hi @Vaibhavs10,
Thank you for your interest in our work!
Indeed we are planning to release training codebase in the near future. 
Regarding collaboration, I will send you a private message via email soon.

**Comment by Vaibhavs10** [comment]
Hey @AvivSham - perfect! I'm at Vaibhav [at] huggingface [dot] co 🤗

**Comment by AvivSham** [comment]
@Vaibhavs10 you should see it in your inbox 🤗

**Comment by YaelSegalFeldman** [comment]
We released the training code
