### ISSUE TITLE
Can't Reproduce Reported WER

### ISSUE THREAD

**Issue by berkind1** [aiola-lab/whisper-medusa#23]
Hi,

I’m really impressed with your project—it's outstanding! I truly appreciate the effort and detail you've put into it. I'm interested in using your Whisper-Medusa model and have been working with the following HF checkpoints on the Librispeech-clean test set:

https://huggingface.co/aiola/whisper-medusa-linear-libri

https://huggingface.co/aiola/whisper-medusa-v1

However, I’ve been unable to achieve a WER below 10%. I used your eval_whisper_medusa.py script for evaluation. Could you please help me replicate the results you reported in your repo (4.1% WER)? I’m testing on an M3 Pro using MPS.

Thanks so much for your help!

**Comment by YaelSegalFeldman** [comment]
Hi,

We ran the [model](https://huggingface.co/aiola/whisper-medusa-linear-libri) and successfully reproduced the results. Could you try running it on Google Colab? The discrepancy might be due to the GPU type, we'd be glad to know if that's the case.

**Comment by berkind1** [comment]
I resolved the issue and successfully reproduced the WER on my M3 Pro. The high WER was due to corrupted files in my data.
