### ISSUE TITLE
Vanilla Whisper Benchmark

### ISSUE THREAD

**Issue by LLMGuru** [aiola-lab/whisper-medusa#25]
Hi,

Could you please clarify what you mean by "vanilla whisper"? I assumed it referred to the original OpenAI Whisper-large-v2 model, but the performance you reported seems to differ from OpenAI’s results. If you check the [Hugging Face ASR leaderboard ](https://huggingface.co/spaces/hf-audio/open_asr_leaderboard), you can see that OpenAI's original model achieves a 2.83% WER on LibriSpeech. However, in your repository, the reported WER for vanilla whisper is 4%.

<img width="1223" alt="Screenshot 2024-10-17 at 10 45 03 AM" src="https://github.com/user-attachments/assets/819b8e84-5746-48d0-aee6-7fdb4246977c">

Since 4% didn't seem accurate to me (it aligns with whisper-base's performance rather than large-v2), I double-checked with other sources and confirmed it should be lower. Am I overlooking something, or is Vanilla Whisper not an OpenAI version?

**Comment by YaelSegalFeldman** [comment]
Hi  @LLMGuru ,
I believe the difference is attributed to the text normalizer. Hugging Face used the EnglishTextNormalizer ([GitHub link](https://github.com/huggingface/open_asr_leaderboard/blob/main/normalizer/normalizer.py)) in their code, whereas we used a different normalizer, which can be found here: [GitHub link](https://github.com/aiola-lab/whisper-medusa/blob/main/whisper_medusa/utils/metrics.py).
