### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by wredan** [aiola-lab/whisper-medusa#26]
Hi, great work so far! Seems promising.

I’d like to deeply fine-tune these two architectures on multilingual datasets because I found the Spanish analysis great. I did not find the training GPU specs used in the docs; I was wondering if it is the same one used to speed evaluations, the NVIDIA A10G GPU. Can you provide info on this topic?

Also, do you guys plan to release the multilingual pretrained model on VoxPopuli?

Thank you in advance

**Comment by YaelSegalFeldman** [comment]
Hi @wredan,
We trained the model using an NVIDIA A10G GPU (g5.2xlarge instance on EC2). As for releasing the pretrained model on VoxPopuli, We don’t know when we will release it yet.

**Comment by YaelSegalFeldman** [comment]
Hi @wredan,
We’ve just released our Medusa-Block multilingual model for English, French, German, and Spanish on VoxPopuli!  
You can download it here: [aiola/whisper-medusa-multilingual](https://huggingface.co/aiola/whisper-medusa-multilingual).

**Comment by wredan** [comment]
Hi @YaelSegalFeldman,

Thank you for sharing! 

Keep up! 👏
