### ISSUE TITLE
Repetition Hallucunation using Top-k Tree Decoding

### ISSUE THREAD

**Issue by ByteSizedBandit** [aiola-lab/whisper-medusa#29]
Hi,

I truly appreciate the excellent work you’ve done. I tested your code on several datasets using your checkpoint and observed a remarkable x1.5 speed-up, which is impressive. However, I am exploring ways to achieve even better speed-ups by incorporating top-k prediction and a tree structure.

To experiment, I used your checkpoint with the following configuration:

Top-1 for the base head and Medusa heads 1–8
Top-3 for Medusa head 9
Top-2 for Medusa head 10
Specifically, the only change in the configuration was:

` medusa_choices: [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 2 ]`

However, this resulted in repetition hallucinations, as shown in the screenshot below:
<img width="1247" alt="Screenshot 2024-12-04 at 4 02 52 PM" src="https://github.com/user-attachments/assets/807cfbc0-1661-4c02-aa82-34539224f5df">

I am wondering whether top-k prediction with tree structure is not currently supported or if this behavior is due to a bug. If top-k is not supported, I am very interested in contributing to its implementation. Could you please point on the changes needed to integrate tree decoding support?

I believe implementing tree attention using your codebase could enable significantly faster generation (potentially ~x1.9 speed-up). Please let me know if you think otherwise or have concerns. I would greatly appreciate it if you could point me to the relevant areas in the codebase to begin this work.

Thank you again for your amazing contributions!

**Comment by YaelSegalFeldman** [comment]
@ByteSizedBandit 
The bug causing this issue has been fixed. The code is now ready for use.
