### ISSUE TITLE
cl : Command line error D8021 : invalid numeric argument '/Wno-register'

### ISSUE THREAD

**Issue by akwin1234** [aiola-lab/whisper-medusa#5]
PYTHON: 3.10
windows 11 64 bit
PS D:\Miscs\transcribe\whisper-medusa> pip install -e .
WARNING: Ignoring invalid distribution -cipy (c:\users\akash\appdata\local\programs\python\python310\lib\site-packages)
Obtaining file:///D:/Miscs/transcribe/whisper-medusa
  Preparing metadata (setup.py) ... done
  WARNING: Ignoring invalid distribution -cipy (c:\users\akash\appdata\local\programs\python\python310\lib\site-packages)
Collecting accelerate==0.27.2 (from medusa-whisper==0.1.0)
  Using cached accelerate-0.27.2-py3-none-any.whl.metadata (18 kB)
Collecting boto3==1.34.82 (from medusa-whisper==0.1.0)
  Using cached boto3-1.34.82-py3-none-any.whl.metadata (6.6 kB)
Collecting jiwer==3.0.3 (from medusa-whisper==0.1.0)
  Using cached jiwer-3.0.3-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: numpy==1.26.4 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from medusa-whisper==0.1.0) (1.26.4)
Requirement already satisfied: pandas==2.2.2 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from medusa-whisper==0.1.0) (2.2.2)
Collecting peft==0.6.2 (from medusa-whisper==0.1.0)
  Using cached peft-0.6.2-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: soundfile==0.12.1 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from medusa-whisper==0.1.0) (0.12.1)
Collecting torch==2.2.2 (from medusa-whisper==0.1.0)
  Using cached torch-2.2.2-cp310-cp310-win_amd64.whl.metadata (26 kB)
Collecting torchaudio==2.2.2 (from medusa-whisper==0.1.0)
  Using cached torchaudio-2.2.2-cp310-cp310-win_amd64.whl.metadata (6.4 kB)
Collecting transformers==4.39.0 (from medusa-whisper==0.1.0)
  Using cached transformers-4.39.0-py3-none-any.whl.metadata (134 kB)
Collecting wandb==0.16.6 (from medusa-whisper==0.1.0)
  Using cached wandb-0.16.6-py3-none-any.whl.metadata (10 kB)
Collecting WeTextProcessing (from medusa-whisper==0.1.0)
  Using cached WeTextProcessing-1.0.4.1-py3-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from accelerate==0.27.2->medusa-whisper==0.1.0) (24.1)
Requirement already satisfied: psutil in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from accelerate==0.27.2->medusa-whisper==0.1.0) (5.9.5)
Requirement already satisfied: pyyaml in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from accelerate==0.27.2->medusa-whisper==0.1.0) (6.0.1)
Requirement already satisfied: huggingface-hub in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from accelerate==0.27.2->medusa-whisper==0.1.0) (0.23.4)
Requirement already satisfied: safetensors>=0.3.1 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from accelerate==0.27.2->medusa-whisper==0.1.0) (0.4.3)
Collecting botocore<1.35.0,>=1.34.82 (from boto3==1.34.82->medusa-whisper==0.1.0)
  Using cached botocore-1.34.152-py3-none-any.whl.metadata (5.7 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3==1.34.82->medusa-whisper==0.1.0)
  Using cached jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.11.0,>=0.10.0 (from boto3==1.34.82->medusa-whisper==0.1.0)
  Using cached s3transfer-0.10.2-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: click<9.0.0,>=8.1.3 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from jiwer==3.0.3->medusa-whisper==0.1.0) (8.1.7)
Collecting rapidfuzz<4,>=3 (from jiwer==3.0.3->medusa-whisper==0.1.0)
  Using cached rapidfuzz-3.9.5-cp310-cp310-win_amd64.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from pandas==2.2.2->medusa-whisper==0.1.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from pandas==2.2.2->medusa-whisper==0.1.0) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from pandas==2.2.2->medusa-whisper==0.1.0) (2024.1)
Requirement already satisfied: tqdm in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from peft==0.6.2->medusa-whisper==0.1.0) (4.66.4)
Requirement already satisfied: cffi>=1.0 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from soundfile==0.12.1->medusa-whisper==0.1.0) (1.16.0)
Requirement already satisfied: filelock in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from torch==2.2.2->medusa-whisper==0.1.0) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from torch==2.2.2->medusa-whisper==0.1.0) (4.12.2)
Requirement already satisfied: sympy in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from torch==2.2.2->medusa-whisper==0.1.0) (1.12)
Requirement already satisfied: networkx in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from torch==2.2.2->medusa-whisper==0.1.0) (3.3)
Requirement already satisfied: jinja2 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from torch==2.2.2->medusa-whisper==0.1.0) (3.1.3)
Requirement already satisfied: fsspec in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from torch==2.2.2->medusa-whisper==0.1.0) (2024.2.0)
Requirement already satisfied: regex!=2019.12.17 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from transformers==4.39.0->medusa-whisper==0.1.0) (2024.5.15)
Requirement already satisfied: requests in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from transformers==4.39.0->medusa-whisper==0.1.0) (2.32.3)
Collecting tokenizers<0.19,>=0.14 (from transformers==4.39.0->medusa-whisper==0.1.0)
  Using cached tokenizers-0.15.2-cp310-none-win_amd64.whl.metadata (6.8 kB)
Requirement already satisfied: GitPython!=3.1.29,>=1.0.0 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from wandb==0.16.6->medusa-whisper==0.1.0) (3.1.43)
Collecting sentry-sdk>=1.0.0 (from wandb==0.16.6->medusa-whisper==0.1.0)
  Using cached sentry_sdk-2.12.0-py2.py3-none-any.whl.metadata (9.8 kB)
Collecting docker-pycreds>=0.4.0 (from wandb==0.16.6->medusa-whisper==0.1.0)
  Using cached docker_pycreds-0.4.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting setproctitle (from wandb==0.16.6->medusa-whisper==0.1.0)
  Using cached setproctitle-1.3.3-cp310-cp310-win_amd64.whl.metadata (10 kB)
Requirement already satisfied: setuptools in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from wandb==0.16.6->medusa-whisper==0.1.0) (68.2.2)
Collecting appdirs>=1.4.3 (from wandb==0.16.6->medusa-whisper==0.1.0)
  Using cached appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: protobuf!=4.21.0,<5,>=3.19.0 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from wandb==0.16.6->medusa-whisper==0.1.0) (4.25.4)
Collecting pynini==2.1.6 (from WeTextProcessing->medusa-whisper==0.1.0)
  Using cached pynini-2.1.6.tar.gz (789 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: importlib-resources in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from WeTextProcessing->medusa-whisper==0.1.0) (6.4.0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from botocore<1.35.0,>=1.34.82->boto3==1.34.82->medusa-whisper==0.1.0) (2.2.1)
Requirement already satisfied: pycparser in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.0->soundfile==0.12.1->medusa-whisper==0.1.0) (2.22)
Requirement already satisfied: colorama in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from click<9.0.0,>=8.1.3->jiwer==3.0.3->medusa-whisper==0.1.0) (0.4.6)
Requirement already satisfied: six>=1.4.0 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from docker-pycreds>=0.4.0->wandb==0.16.6->medusa-whisper==0.1.0) (1.16.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from GitPython!=3.1.29,>=1.0.0->wandb==0.16.6->medusa-whisper==0.1.0) (4.0.11)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers==4.39.0->medusa-whisper==0.1.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers==4.39.0->medusa-whisper==0.1.0) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers==4.39.0->medusa-whisper==0.1.0) (2024.6.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from jinja2->torch==2.2.2->medusa-whisper==0.1.0) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from sympy->torch==2.2.2->medusa-whisper==0.1.0) (1.3.0)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\akash\appdata\local\programs\python\python310\lib\site-packages (from gitdb<5,>=4.0.1->GitPython!=3.1.29,>=1.0.0->wandb==0.16.6->medusa-whisper==0.1.0) (5.0.1)
Using cached accelerate-0.27.2-py3-none-any.whl (279 kB)
Using cached boto3-1.34.82-py3-none-any.whl (139 kB)
Using cached jiwer-3.0.3-py3-none-any.whl (21 kB)
Using cached peft-0.6.2-py3-none-any.whl (174 kB)
Using cached torch-2.2.2-cp310-cp310-win_amd64.whl (198.6 MB)
Using cached torchaudio-2.2.2-cp310-cp310-win_amd64.whl (2.4 MB)
Using cached transformers-4.39.0-py3-none-any.whl (8.8 MB)
Using cached wandb-0.16.6-py3-none-any.whl (2.2 MB)
Using cached WeTextProcessing-1.0.4.1-py3-none-any.whl (2.0 MB)
Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Using cached botocore-1.34.152-py3-none-any.whl (12.4 MB)
Using cached docker_pycreds-0.4.0-py2.py3-none-any.whl (9.0 kB)
Using cached jmespath-1.0.1-py3-none-any.whl (20 kB)
Using cached rapidfuzz-3.9.5-cp310-cp310-win_amd64.whl (1.7 MB)
Using cached s3transfer-0.10.2-py3-none-any.whl (82 kB)
Using cached sentry_sdk-2.12.0-py2.py3-none-any.whl (301 kB)
Using cached tokenizers-0.15.2-cp310-none-win_amd64.whl (2.2 MB)
Using cached setproctitle-1.3.3-cp310-cp310-win_amd64.whl (11 kB)
Building wheels for collected packages: pynini
  Building wheel for pynini (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pynini (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [69 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\pynini
      copying pynini\__init__.py -> build\lib.win-amd64-cpython-310\pynini
      creating build\lib.win-amd64-cpython-310\pywrapfst
      copying pywrapfst\__init__.py -> build\lib.win-amd64-cpython-310\pywrapfst
      creating build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\case.py -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\chatspeak.py -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\chatspeak_model.py -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\dates.py -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\g2p.py -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\numbers.py -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\plurals.py -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\t9.py -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\weather.py -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\__init__.py -> build\lib.win-amd64-cpython-310\pynini\examples
      creating build\lib.win-amd64-cpython-310\pynini\export
      copying pynini\export\export.py -> build\lib.win-amd64-cpython-310\pynini\export
      copying pynini\export\grm.py -> build\lib.win-amd64-cpython-310\pynini\export
      copying pynini\export\grm_example.py -> build\lib.win-amd64-cpython-310\pynini\export
      copying pynini\export\multi_grm.py -> build\lib.win-amd64-cpython-310\pynini\export
      copying pynini\export\multi_grm_example.py -> build\lib.win-amd64-cpython-310\pynini\export
      copying pynini\export\__init__.py -> build\lib.win-amd64-cpython-310\pynini\export
      creating build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\byte.py -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\edit_transducer.py -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\features.py -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\paradigms.py -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\pynutil.py -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\rewrite.py -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\rule_cascade.py -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\stringfile.py -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\tagger.py -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\utf8.py -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\__init__.py -> build\lib.win-amd64-cpython-310\pynini\lib
      running egg_info
      writing pynini.egg-info\PKG-INFO
      writing dependency_links to pynini.egg-info\dependency_links.txt
      writing top-level names to pynini.egg-info\top_level.txt
      reading manifest file 'pynini.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      adding license file 'AUTHORS'
      writing manifest file 'pynini.egg-info\SOURCES.txt'
      copying pynini\BUILD.bazel -> build\lib.win-amd64-cpython-310\pynini
      copying pynini\__init__.pyi -> build\lib.win-amd64-cpython-310\pynini
      copying pynini\py.typed -> build\lib.win-amd64-cpython-310\pynini
      copying pywrapfst\BUILD.bazel -> build\lib.win-amd64-cpython-310\pywrapfst
      copying pywrapfst\__init__.pyi -> build\lib.win-amd64-cpython-310\pywrapfst
      copying pywrapfst\py.typed -> build\lib.win-amd64-cpython-310\pywrapfst
      copying pynini\examples\BUILD.bazel -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\py.typed -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\export\BUILD.bazel -> build\lib.win-amd64-cpython-310\pynini\export
      copying pynini\export\grm_py_build_defs.bzl -> build\lib.win-amd64-cpython-310\pynini\export
      copying pynini\export\py.typed -> build\lib.win-amd64-cpython-310\pynini\export
      copying pynini\lib\BUILD.bazel -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\py.typed -> build\lib.win-amd64-cpython-310\pynini\lib
      running build_ext
      building '_pywrapfst' extension
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      creating build\temp.win-amd64-cpython-310\Release\extensions
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\akash\AppData\Local\Programs\Python\Python310\include -IC:\Users\akash\AppData\Local\Programs\Python\Python310\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpextensions/_pywrapfst.cpp /Fobuild\temp.win-amd64-cpython-310\Release\extensions/_pywrapfst.obj -std=c++17 -Wno-register -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-local-typedefs -funsigned-char
      cl : Command line error D8021 : invalid numeric argument '/Wno-register'
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pynini
Failed to build pynini
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pynini)
PS D:\Miscs\transcribe\whisper-medusa>

i have all C++ sdk and etc installed in/via visual studio 

how do i fix it?

**Comment by AvivNavon** [comment]
Hi, we have cleaned up some dependancies, please pull `main` and try again now

**Comment by akwin1234** [comment]
> Hi, we have cleaned up some dependancies, please pull `main` and try again now

worked now, thank you
