### ISSUE TITLE
Add more information to the 🤗 Hugging Face Hub model repo

### ISSUE THREAD

**Issue by Vaibhavs10** [aiola-lab/whisper-medusa#6]
Heya, Congrats on the brilliant research!

I'm VB. I work in the open-source team at Hugging Face. I saw that you've uploaded the model checkpoints [here](https://huggingface.co/aiola/whisper-medusa-v1), however the model repo has no README and is quite bare at the moment.

It'd be great if you could populate it with usage examples, code snippets and more details about your research and so on.

It's nice to see Transformers being used out in the Wild. Do let us know if we can help in any way! 🤗

Cheers,
VB

**Comment by AvivSham** [comment]
Hi @Vaibhavs10,
Thank you for your interest in our work!
We have updated the [model card](https://huggingface.co/aiola/whisper-medusa-v1), feel free to have a look.
